export const MOTIVATIONAL_TEXTS = [
    "Decarbonize today for a sustainable tomorrow.",
    "Every project counts. Build green, build smart.",
    "Empowering the built environment to achieve net zero.",
    "Sustainability starts with a single step. Take yours now.",
    "Reduce emissions, enhance biodiversity, and thrive.",
    "The future is green. Let's build it together.",
    "Carbon intelligence for a cleaner planet.",
    "Small changes, big impact. Decarbonize your projects.",
    "Innovate. Collaborate. Decarbonize.",
    "Your projects can change the world. Make them sustainable.",
    "Track, reduce, and achieve your carbon goals.",
    "Sustainability is not a choice; it's a responsibility.",
    "Build with purpose. Build for the planet.",
    "Together, we can solve the carbon crisis.",
    "Green buildings, brighter futures.",
    "Decarbonization made simple. Start today.",
    "Empowering you to build a net-zero future.",
    "Sustainability is the foundation of progress.",
    "Turn data into action. Decarbonize smarter.",
    "The built environment's carbon solution starts here.",
    "Innovate sustainably. Lead responsibly.",
    "Your projects, your legacy. Make them green.",
    "Sustainability is the blueprint for tomorrow.",
    "Decarbonize with confidence. We've got your back.",
    "Every decision matters. Choose sustainability.",
    "Build better. Build greener. Build with Carbonetrix.",
    "The road to net zero starts with you.",
    "Sustainability is the ultimate innovation.",
    "Transform your projects. Transform the planet.",
    "Join the movement. Decarbonize the built environment."
]; 